### ISSUE TITLE
use ts builder api

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor-book#13]
adjust all client code in the book and the `/programs` folder to use the new `program.methods` API.

The PDA inference is still behind a feature gate and should not be included in the book yet.

**Comment by LoneStarDev** [comment]
Is there anything a newbie can do here?

**Comment by paul-schaaf** [comment]
yea totally this is pretty straightforward to do!

just a switch from one syntax to another

**Comment by LoneStarDev** [comment]
let me take a look. Im newish to Git and coding in general. Created a couple simple programs with anchor. Trying to figure out how to contribute, but one has to have knowledge to do so. Only learn by doing I guess. Thanks Paul!

**Comment by LoneStarDev** [comment]
by any chance could you point me to where the new program.methods API is? Documentation? I am assuming the task is to replace the old methods with the new methods right?

**Comment by paul-schaaf** [comment]
yes that is the task. theres no documentation. check out the tests/pda-derivation dir in the repo for examples

**Comment by LoneStarDev** [comment]
I probably don't have the skillset yet for this. I will be interested once someone does this so I have reference to what this all means.

**Comment by lucasig11** [comment]
can i work on this?

**Comment by paul-schaaf** [comment]
@lucasig11 yes!
