### ISSUE TITLE
Cargo cannot install avm

### ISSUE THREAD

**Issue by JayBee007** [project-serum/anchor-book#53]
On executing the following command from anchor-book `cargo install --git https://github.com/project-serum/anchor avm --locked --force`, it fails with an error _error: could not find `avm` in https://github.com/project-serum/anchor with version `*`_

**Comment by paul-schaaf** [comment]
sorry just saw this now. Im not able to reproduce it though. can you share some more details about your local environment?

**Comment by JayBee007** [comment]
@paul-schaaf It did install avm this time, ` Installing avm v0.24.2 (https://github.com/project-serum/anchor#0b4c7b0c)` cannot figure out what was the issue, but I guess that may be recently the version was locked from `*` to `0.24.2`, thanks for replying, closing the issue.
