### ISSUE TITLE
Splitting program into multiple files failed 

### ISSUE THREAD

**Issue by oulaoba** [project-serum/anchor-book#96]
I am success in this *tic_tac_toe project,But* when i try to split program into multiple files. the program doesn't work. the error message is *unresolved import `crate`*,but i think my program is same to this example.
<img width="1567" alt="image" src="https://github.com/coral-xyz/anchor-book/assets/34548001/fcb609be-d2bd-496e-ba3e-b0b93fd2fbc3">

**Comment by acheroncrypto** [comment]
You can check out multiple file example with `anchor init example --template multiple` or `anchor new example --template multiple`.

Please use [Solana StackExchange](https://solana.stackexchange.com/) or [Anchor Discord](https://discord.gg/NHHGSXAnXk) to ask questions instead.
